name: Deployment

on:
  push:
    branches:
      - master

jobs:
  setting_up:
    name: Setting project
    runs-on: ubuntu-latest
    steps:
      # Checkout, Cache and Setup Steps
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      # Installing library requirements
      - name: Install node modules
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Compile contracts
        run: yarn build

  deploy_kovan:
    name: Deploy Contracts to Kovan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Migrate
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: yarn migrate kovan
