name: Migrate
on:
  push:
    tags: '*'
    branches-ignore: '*'

jobs:
  migrate:
    name: Migrate Contracts
    runs-on: ubuntu-latest
    steps:
      # Checkout, Cache and Setup Steps
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.9.1
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Cache contracts
        id: cache-contracts
        uses: actions/cache@v1
        with:
          path: contracts
          key: ${{ runner.OS }}-build-${{ hashFiles('contracts/**/*.sol') }}
      # Installing library requirements
      - name: Install node modules
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          yarn policies set-version 1.19.2
          yarn install --frozen-lockfile
      # Compile contracts
      - name: Compile contracts
        if: steps.cache-contracts.outputs.cache-hit != 'true'
        run: |
          yarn policies set-version 1.19.2
          yarn build
      - name: Get tag
        run: echo ::set-env name=TAG::${GITHUB_REF#refs/*/}
      - name:
        run: echo $TAG
      # Migrate contracts
      # - name: Migrate to Kovan
      #   env:
      #     PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      #     INFURA: ${{ secrets.INFURA }}
      #     ETHERSCAN: ${{ secrets.ETHERSCAN }}
      #   run: |
      #     yarn policies set-version 1.19.2
      #     yarn migrate kovan
# node -p -e "Object.keys(require('./truffle-networks')).includes('xdai')"
